### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by kloppstock** [kloppstock/texture_generator#9]
Write tests for all necessary methods:
 - [x] Tests for ImageCreation (#5)
 - [x] Tests for ImageManipulation (#6)
 - [x] Tests for ImageGetter (#7)
 - [x] Tests for Matrix2D (#8)
 - [x] integration tests

Note:
 * Simple getter and setter methods are not tested
 * GUI methods are not tested
